### Objectives
- Load the dataset
- Handle missing values
- Remove duplicates
- Create missing value indicator features
- Clean and normalize text
- Create text statistics
- Save the processed dataset

In [ ]:
import pandas as pd
import numpy as np

import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("NLTK resources are ready!")

NLTK resources are ready!

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [ ]:
df = pd.read_csv("../data/raw/fake_job_postings.csv")

print("Dataset loaded successfully!")

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

display(df.head())

Dataset loaded successfully!
Rows : 17880
Columns : 18

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [ ]:
print("="*60)
print("Dataset Information")
print("="*60)

df.info()

print("\nMissing Values")

display(
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

============================================================
Dataset Information
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  str
 2   location             17534 non-null  str
 3   department           6333 non-null   str
 4   salary_range         2868 non-null   str
 5   company_profile      14572 non-null  str
 6   description          17879 non-null  str
 7   requirements         15184 non-null  str
 8   benefits             10668 non-null  str
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  str
 13  required_experience  10830 non-null  str
 14  required_education   9775 non-null   str
 15  industry             12977 non-null  str
 16  function             11425 non-null  str
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), str(13)
memory usage: 49.6 MB

Missing Values

salary_range           15012
department             11547
required_education      8105
benefits                7212
required_experience     7050
function                6455
industry                4903
employment_type         3471
company_profile         3308
requirements            2696
location                 346
description                1
title                      0
job_id                     0
telecommuting              0
has_questions              0
has_company_logo           0
fraudulent                 0
dtype: int64

In [ ]:
df = df.dropna(subset=["description"])

print("Rows after removing missing description:", len(df))

Rows after removing missing description: 17879

In [ ]:
indicator_columns = [
    "salary_range",
    "department",
    "company_profile",
    "requirements",
    "benefits"
]

for col in indicator_columns:
    df[col + "_missing"] = df[col].isna().astype(int)

df[[c + "_missing" for c in indicator_columns]].head()

,salary_range_missing,department_missing,company_profile_missing,requirements_missing,benefits_missing
0,1,0,0,0,1
1,1,0,0,0,0
2,1,1,0,0,1
3,1,0,0,0,0
4,1,1,0,0,0

In [ ]:
fill_values = {
    "salary_range": "Not Specified",
    "department": "Not Specified",
    "company_profile": "",
    "requirements": "",
    "benefits": "",
    "employment_type": "Unknown",
    "required_experience": "Unknown",
    "required_education": "Unknown",
    "industry": "Unknown",
    "function": "Unknown",
    "location": "Unknown"
}

df.fillna(fill_values, inplace=True)

print("Missing values handled successfully.")

Missing values handled successfully.

In [ ]:
df.isnull().sum()

job_id                     0
title                      0
location                   0
department                 0
salary_range               0
company_profile            0
description                0
requirements               0
benefits                   0
telecommuting              0
has_company_logo           0
has_questions              0
employment_type            0
required_experience        0
required_education         0
industry                   0
function                   0
fraudulent                 0
salary_range_missing       0
department_missing         0
company_profile_missing    0
requirements_missing       0
benefits_missing           0
dtype: int64

In [ ]:
df.drop(columns=["job_id"], inplace=True)

print("job_id removed successfully.")

job_id removed successfully.

In [ ]:
text_columns = [
    "title",
    "company_profile",
    "description",
    "requirements",
    "benefits"
]

df["combined_text"] = df[text_columns].agg(" ".join, axis=1)

df["combined_text"].head()

0    Marketing Intern We're Food52, and we've creat...
1    Customer Service - Cloud Video Production 90 S...
2    Commissioning Machinery Assistant (CMA) Valor ...
3    Account Executive - Washington DC Our passion ...
4    Bill Review Manager SpotSource Solutions LLC i...
Name: combined_text, dtype: str

In [ ]:
import re
import string

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    text = text.lower()

    # Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove email addresses
    text = re.sub(r"\S+@\S+", " ", text)

    # Remove numbers
    text = re.sub(r"\d+", " ", text)

    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Tokenize
    words = text.split()

    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

df["clean_text"] = df["combined_text"].apply(clean_text)

df[["combined_text", "clean_text"]].head()

,combined_text,clean_text
0,"Marketing Intern We're Food52, and we've creat...",marketing intern food weve created groundbreak...
1,Customer Service - Cloud Video Production 90 S...,customer service cloud video production second...
2,Commissioning Machinery Assistant (CMA) Valor ...,commissioning machinery assistant cma valor se...
3,Account Executive - Washington DC Our passion ...,account executive washington dc passion improv...
4,Bill Review Manager SpotSource Solutions LLC i...,bill review manager spotsource solution llc gl...

In [ ]:
# ==========================================================
# Create Text Statistics
# ==========================================================

df["text_length"] = df["clean_text"].str.len()

df["word_count"] = df["clean_text"].apply(lambda x: len(x.split()))

df["avg_word_length"] = (
    df["clean_text"]
      .apply(
          lambda x: np.mean([len(word) for word in x.split()])
          if len(x.split()) > 0 else 0
      )
)

print("Text statistics created successfully.")

df[
    [
        "text_length",
        "word_count",
        "avg_word_length"
    ]
].head()

Text statistics created successfully.

   text_length  word_count  avg_word_length
0         2003         242         7.280992
1         4088         529         6.729679
2         1994         218         8.151376
3         4433         479         8.256785
4         3220         354         8.098870

In [ ]:
# ==========================================================
# Select Final Features
# ==========================================================

processed_df = df[
    [
        "clean_text",

        "text_length",
        "word_count",
        "avg_word_length",

        "telecommuting",
        "has_company_logo",
        "has_questions",

        "employment_type",
        "required_experience",
        "required_education",
        "industry",
        "function",

        "salary_range_missing",
        "department_missing",
        "company_profile_missing",
        "requirements_missing",
        "benefits_missing",

        "fraudulent"
    ]
]

print("Final dataset created successfully.")

processed_df.head()

Final dataset created successfully.

,clean_text,text_length,word_count,avg_word_length,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,salary_range_missing,department_missing,company_profile_missing,requirements_missing,benefits_missing,fraudulent
0,marketing intern food weve created groundbreak...,2003,242,7.280992,0,1,0,Other,Internship,Unknown,Unknown,Marketing,1,0,0,0,1,0
1,customer service cloud video production second...,4088,529,6.729679,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,1,0,0,0,0,0
2,commissioning machinery assistant cma valor se...,1994,218,8.151376,0,1,0,Unknown,Unknown,Unknown,Unknown,Unknown,1,1,0,0,1,0
3,account executive washington dc passion improv...,4433,479,8.256785,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,1,0,0,0,0,0
4,bill review manager spotsource solution llc gl...,3220,354,8.098870,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,1,1,0,0,0,0

In [ ]:
# ==========================================================
# Dataset Information
# ==========================================================

print("=" * 60)
print("Processed Dataset Information")
print("=" * 60)

processed_df.info()

print("\nShape of Dataset")

print(processed_df.shape)

============================================================
Processed Dataset Information
============================================================
<class 'pandas.DataFrame'>
Index: 17879 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   clean_text               17879 non-null  str
 1   text_length              17879 non-null  int64
 2   word_count               17879 non-null  int64
 3   avg_word_length          17879 non-null  float64
 4   telecommuting            17879 non-null  int64
 5   has_company_logo         17879 non-null  int64
 6   has_questions            17879 non-null  int64
 7   employment_type          17879 non-null  str
 8   required_experience      17879 non-null  str
 9   required_education       17879 non-null  str
 10  industry                 17879 non-null  str
 11  function                 17879 non-null  str
 12  salary_range_missing     17879 non-null  int64
 13  department_missing       17879 non-null  int64
 14  company_profile_missing  17879 non-null  int64
 15  requirements_missing     17879 non-null  int64
 16  benefits_missing         17879 non-null  int64
 17  fraudulent               17879 non-null  int64
dtypes: float64(1), int64(11), str(6)
memory usage: 38.2 MB

Shape of Dataset
(17879, 18)

In [ ]:
# ==========================================================
# Save Processed Dataset
# ==========================================================

import os

os.makedirs("../data/processed", exist_ok=True)

processed_df.to_csv(
    "../data/processed/processed_jobs.csv",
    index=False
)

print("=" * 60)
print("Processed dataset saved successfully!")
print("=" * 60)
print("Location: ../data/processed/processed_jobs.csv")

============================================================
Processed dataset saved successfully!
============================================================
Location: ../data/processed/processed_jobs.csv

In [ ]:
# ==========================================================
# Verify Processed Dataset
# ==========================================================

print("Shape:", processed_df.shape)

print("\nMissing Values:")
print(processed_df.isnull().sum())

print("\nFraud Distribution:")
print(processed_df["fraudulent"].value_counts())

Shape: (17879, 18)

Missing Values:
clean_text                 0
text_length                0
word_count                 0
avg_word_length            0
telecommuting              0
has_company_logo           0
has_questions              0
employment_type            0
required_experience        0
required_education         0
industry                   0
function                   0
salary_range_missing       0
department_missing         0
company_profile_missing    0
requirements_missing       0
benefits_missing           0
fraudulent                 0
dtype: int64

Fraud Distribution:
fraudulent
0    17014
1      865
Name: count, dtype: int64